use LIBRARYDB;

CREATE TABLE BOOK(
	BOOK_ID INT PRIMARY KEY,
    TITLE VARCHAR(30),
    PUBLISH_DATE DATE );
    
INSERT INTO BOOK VALUES('101' , "IT STARTS WITH US" , '2000-02-11');
INSERT INTO BOOK VALUES('102' , "IT ENDS WITH US" , '2006-03-13');
INSERT INTO BOOK VALUES('103' , "TOO GOOD TO BE TRUE" , '1993-09-01');
INSERT INTO BOOK VALUES('104' , "ATOMIC HABITS" , '1991-12-08');
INSERT INTO BOOK VALUES('105' , "THE GAME OF THRONES" , '2015-06-20');

SELECT * FROM BOOK;

SELECT YEAR(PUBLISH_DATE) AS PUBLISHED_YEAR FROM BOOK;

SELECT COUNT(*) AS TOTAL_BOOKS FROM BOOK;

SELECT MIN(PUBLISH_DATE) AS EARLIEST_PUBLISH, MAX(PUBLISH_DATE) AS LATEST_PUBLISH FROM BOOK;

ALTER TABLE BOOK ADD PRICE INT;

UPDATE BOOK 
SET PRICE = 500
WHERE BOOK_ID = "101";

UPDATE BOOK 
SET PRICE = 550
WHERE BOOK_ID = "102";

UPDATE BOOK 
SET PRICE = 399
WHERE BOOK_ID = "103";

UPDATE BOOK 
SET PRICE = 700
WHERE BOOK_ID = "104";

UPDATE BOOK 
SET PRICE = 899
WHERE BOOK_ID = "105";

INSERT INTO BOOK VALUES('106' , "IKIGAI" , '2000-09-29', '1000');

SELECT AVG(PRICE) AS AVG_2000 FROM BOOK WHERE YEAR(PUBLISH_DATE) = 2000;

SELECT UPPER(TITLE) AS BOOKNAME_UPPER, LOWER(TITLE) AS BOOKNAME_LOWER FROM BOOK;

SELECT TITLE FROM BOOK WHERE YEAR(PUBLISH_DATE) BETWEEN 1990 AND 2000;

SELECT TITLE FROM BOOK WHERE TITLE NOT LIKE 'THE%';

SELECT TITLE, PUBLISH_DATE FROM BOOK 
WHERE TITLE LIKE 'A%' AND YEAR(PUBLISH_DATE) > '1970';

SELECT CONCAT(BOOK_ID, '-', TITLE) FROM BOOK;

SELECT LENGTH(TITLE) FROM BOOK;

SELECT UPPER(TITLE), LOWER(TITLE) FROM BOOK;

SELECT SUBSTR('IKIGAI', 1,4) AS SUBSTREX;

SELECT NOW();

SELECT SUBSTR(PUBLISH_DATE, 1, 4) AS PUBYEAR FROM BOOK;


