CREATE DATABASE DBMS;
USE DBMS;
CREATE TABLE STUDENT(
USN VARCHAR(30) PRIMARY KEY,
NAME VARCHAR(40) NOT NULL,
DEPT VARCHAR(20));

INSERT INTO STUDENT VALUES("1RUA24SCS0068", "NISHIT", "CSE");

DESCRIBE STUDENT;
SELECT * FROM STUDENT;

ALTER TABLE STUDENT
ADD EMAIL VARCHAR(20);

ALTER TABLE STUDENT
MODIFY NAME VARCHAR(10);
describe STUDENT;

